Retrieve current ManagedSpan to enable explicit release
opentracing-contrib/java-spanmanager pull request #3
Opened 2017-02-09 09:26 UTC by objectiser

Found an issue when trying to instrument Camel - the `SpanManager` returns a `ManagedSpan` when managing a span - but that span can only be released via the `ManagedSpan`.

If the instrumented application needs to `manage` and `release` in separate locations (i.e. separate callbacks on an exchange handler), then it is not possible to perform the release without stashing the ManagedSpan somewhere - which is the precise problem it is trying to resolve.

This PR makes a slight change to the SpanManager API so that it returns a `ManagedSpan` when calling `currentSpan()` (method could be renamed, e.g. 'current()'?), allowing the code that finishes the span to then release it. The other approach that could be used would be to add a `release` method to the `SpanManager` to obtain the `refreshCurrent()` value and release it - which would be less of a change? Happy to discuss alternatives.

2017-02-09 18:44 UTC, sjoerdtalsma commented
I prefer adding a `current()` method that returns the current `ManagedSpan` instance (that is actually how my own [context-propagation](https://github.com/talsma-ict/context-propagation) API works too 😉.

We can then deprecate the `currentSpan()` method and leave it in for one more revision for people to adopt to this change.

2017-02-09 20:19 UTC, objectiser commented
That is fine with me - I'll update the PR tomorrow.

2017-02-09 20:27 UTC, sjoerdtalsma commented
@objectiser That would be great, thanks!

2017-02-10 06:53 UTC, sjoerdtalsma commented
Maybe we should hold off on adding to the `SpanManager` interface until issue [Should ManagedSpan become ManagedSpanContext?](#5) settles?

2017-02-11 00:39 UTC, objectiser commented
@sjoerdtalsma Thought I would just update based on your previous suggestion - just in case the decision is to keep using the Span instead of SpanContext.

2017-02-12 11:29 UTC, objectiser commented
@sjoerdtalsma Given that there seems to be convergence in https://github.com/opentracing-contrib/java-spanmanager/issues/5 on propagating spans, is it ok to proceed with this PR?

2017-02-12 19:42 UTC, sjoerdtalsma commented
@objectiser I think so; either way returning the `Managed` object (span or context) seems a good idea to me.

2017-02-12 19:46 UTC, sjoerdtalsma approved these changes
Minor typo.
I think we need to think about what the 'empty' ManagedSpan means.
That discussion can be separate from this PR.

2017-02-12 19:46 UTC, sjoerdtalsma commented on src/main/java/io/opentracing/contrib/spanmanager/SpanManager.java
> +     * Return the current <{@link ManagedSpan}.
typo (extra ``<``)

2017-02-12 20:10 UTC, objectiser commented
@sjoerdtalsma Agree empty span needs to be considered separately based on the outcome of the discussions on https://github.com/opentracing/specification/issues/33.

btw could a 0.0.2 (or 0.1.0) release be done after this issue is merged?

2017-02-13 07:36 UTC, sjoerdtalsma commented
@objectiser If it's up to me we could do a release soon.
The library is documented to be in-progress and the current behaviour continues to work (deprecated) for one more revision.

Since there haven't been any other participants in this PR yet, shall we give it 24h to see if others have any objections?

2017-02-13 17:14 UTC, bensigelman commented
@sjoerdtalsma I like the idea of returning the `ManagedSpan` from `current()` for the reason you cited. I am less sure about returning a `noop` instance, though... is that needed for your use case somehow? If so, why? I can see it causing problems, as it becomes harder (IMO) than it used to be to figure out if there is or is not a managed span in the current thread.

2017-02-13 17:30 UTC, objectiser commented
@bensigelman We have been discussing this issue in https://github.com/opentracing-contrib/java-spanmanager/issues/4 - agree null would be better if no managed span exists.

2017-02-14 09:01 UTC, objectiser commented
@sjoerdtalsma As the `current` method is new, should we take this opportunity to return null if no managed span, and then deal with adding null childOf ref in the spec repo?

2017-02-14 09:24 UTC, sjoerdtalsma commented
@objectiser That was my intention right after this merge :smile:

2017-02-14 09:27 UTC, objectiser commented
@sjoerdtalsma Ok will update the PR to return null - do you want the commits squashed?

2017-02-14 09:28 UTC, sjoerdtalsma commented
Github has the "Squash and merge" option, so whatever is easier for you.

2017-02-14 09:52 UTC, objectiser commented
@sjoerdtalsma Good point :) - I'll leave to you. Hopefully this update should do it, but let me know if anything.

2017-02-14 10:04 UTC, sjoerdtalsma requested changes
I really don't like returning `null` ManagedSpan references. I have no objection to 'empty' managed spans that contain `null` Span references, but I would like `current()` to always return a ManagedSpan instance.
Let's document that it can be empty though!

2017-02-14 10:04 UTC, sjoerdtalsma commented on src/main/java/io/opentracing/contrib/spanmanager/SpanManager.java
> +     * @return The current ManagedSpan or null if there is no managed span.
I think I misunderstood.
For semantics, I think we can return an EmptyManagedSpan / NoManagedSpan constant here, that contains a `null` Span.
That way for Java-8, we could add `Optional`-like methods to the interface providing a `getOrElse(Span)` or `ifPresent(Consumer<Span>)` default method.

I thought you would change the getSpan() to return `null`.

2017-02-14 10:38 UTC, sjoerdtalsma commented on src/main/java/io/opentracing/contrib/spanmanager/SpanManager.java
> +     * @return The current ManagedSpan or null if there is no managed span.
I am willing to do this separately from this PR too, just let me know.

2017-02-14 11:08 UTC, objectiser commented
@sjoerdtalsma Sorry misunderstood - updated.

2017-02-14 11:42 UTC, sjoerdtalsma approved these changes

2017-02-14 18:14 UTC, merged

2017-02-15 08:03 UTC, objectiser commented
@sjoerdtalsma Thanks! Would it be possible to do a release 0.0.2 or preferrably 0.1.0 today?

2017-02-15 09:33 UTC, sjoerdtalsma commented
@objectiser 0.0.2 was released yesterday.
It is already available on maven-central: http://repo1.maven.org/maven2/io/opentracing/contrib/opentracing-spanmanager/0.0.2/

Maybe there's a mirror you use that was not yet synchronized?

2017-02-15 09:47 UTC, objectiser commented
@sjoerdtalsma Ok thanks